[project]
name = "Smart-Teddy"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "hk2505", email = "kh8599@mci4me.at"},
]
dependencies = []
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
